name: cli checks
run-name: CLI checks

on:
  push:
    branches: "main"

jobs:
  CLI_CHECKING:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/devops-hemant/deployment:v0.0.2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHTOKEN }}
    permissions:
      issues: write
      pull-requests: write
    steps:
    - run: databricks --version 
    - run: az --version
    - run: dbsqlcli --help
    - run: yq --version
